# Generated by Django 4.1 on 2022-08-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom', '0002_book_created_at_book_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Book_Category',
                'verbose_name_plural': 'Book_Categories',
            },
        ),
    ]
