# Generated by Django 4.1 on 2022-08-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom', '0004_category_book_category_alter_book_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSellerBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('rank', models.CharField(max_length=10)),
            ],
        ),
    ]
