# Generated by Django 4.1 on 2022-08-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkField', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('rank', models.CharField(max_length=100)),
                ('book', models.CharField(max_length=100)),
            ],
        ),
    ]
