# Generated by Django 2.2.12 on 2022-09-12 12:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LinkField', '0003_rename_book_bestseller_book_name_book_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='modified_on',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 9, 12, 12, 36, 40, 231768, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bestseller',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
